# Define the version of Docker Compose.
version: "3.7"

# Define the services to be run by Docker Compose.
services:
  web:
    # Define the build context as the current directory and the Dockerfile to be used as Dockerfile.prod.
    build:
      context: .
      dockerfile: Dockerfile
    # Define the container name.
    container_name: demo-docker-nextjs

    # Maps the ports to be exposed on the host.
    ports:
      - "3000:3000"
    # Define the environment file to be used.
    env_file:
      - .env.docker

# Define the volumes to be used.
# The node_modules volume is used to persist project dependencies between containers.
volumes:
  node_modules:
