name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - name: Checkout
        uses: actions/checkout@v4

      - name: config aws credetials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{secrets.AWS_REGION}}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create env file
        run: |
          touch .env
          echo S3_REGION=${{secrets.AWS_REGION}} >> .env
          echo DOMAIN=${{secrets.DOMAIN}} >> .env
          echo S3_BUCKET=${{secrets.AWS_BUCKET}} >> .env
          cat .env

      - name: Build the Docker image
        env:
          ECR_URI: ${{secrets.ECR_URI}}
        run: |
          docker build -t next-project .
          docker tag next-project:latest $ECR_URI:latest
          docker push $ECR_URI
